services:
  otel-collector:
    image: otel/opentelemetry-collector
    networks:
      - tracking_network
    ports:
      - "4317:4317"
    volumes:
      - ./otel-collector-config.yaml:/etc/otel/config.yaml
