services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: tracking_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    networks:
      - tracking_network
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "user", "-d", "tracking_db" ]
      interval: 10s
      retries: 5
