services:
  promtail:
    image: grafana/promtail:latest
    networks:
      - tracking_network
    volumes:
      - /var/log:/var/log
      - ./infrastructure/promtail-config.yaml:/etc/promtail/promtail-config.yaml
    command: -config.file=/etc/promtail/promtail-config.yaml
