services:
  storage:
    build:
      context: ..
      dockerfile: services/storage/Dockerfile
    env_file:
      - ../services/storage/.env
    networks:
      - tracking_network
    depends_on:
      mongodb:
        condition: service_healthy
      postgres:
        condition: service_healthy
    ports:
      - "8040:8040"
