global:
  resolve_timeout: 5m

route:
  group_by: ["job"]
  group_wait: 10s
  group_interval: 5m
  repeat_interval: 3h
  receiver: "default"

receivers:
  - name: "default"
    webhook_configs:
      - url: "http://webhook-service:5000"
