global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: "tracking"
    metrics_path: /metrics
    static_configs:
      - targets: ["tracking:8000"]

  - job_name: "ingestion"
    metrics_path: /metrics
    static_configs:
      - targets: ["ingestion:8020"]

  - job_name: "processing"
    metrics_path: /metrics
    static_configs:
      - targets: ["processing:8030"]

  - job_name: "storage"
    metrics_path: /metrics
    static_configs:
      - targets: ["storage:8040"]
